export type Phase = "load" | "explode" | "drive" | "balanced";
export type Vector = "horizontal" | "vertical" | "rotational" | "lateral";
export type ContractionType = "concentric" | "eccentric" | "isometric" | "plyometric" | "reactive";
export type Section = "warmup" | "activation" | "plyometrics" | "strength" | "speed" | "preventive" | "cooldown";
export type FatigueLevel = "low" | "medium" | "high";
export type IntensityLevel = "low" | "medium" | "high" | "max";

export interface Exercise {
  id: string;
  name: string;
  section: Section;
  phase: Phase;
  vector: Vector;
  contractionType: ContractionType;
  neuromuscularLoad: 1 | 2 | 3 | 4 | 5;
  fatigueGenerated: FatigueLevel;
  transfer: string;
  defaultSets: number;
  defaultReps: number | null;
  defaultDuration: number | null; // seconds, if time-based
  defaultRest: number; // seconds
  intensityLevel: IntensityLevel;
  coachingCues: string[];
  physiologicalObjective: string;
  equipment: string;
  safeForInjury: boolean;
}

export const EXERCISES: Exercise[] = [
  // ─── WARMUP ───────────────────────────────────────────────────────────────
  {
    id: "wu-01",
    name: "Footing progresivo",
    section: "warmup",
    phase: "balanced",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Elevación de temperatura central y flujo sanguíneo periférico",
    defaultSets: 1,
    defaultReps: null,
    defaultDuration: 480,
    defaultRest: 0,
    intensityLevel: "low",
    coachingCues: [
      "Mantén una cadencia de 140-150 ppm",
      "Contacto suave del pie con el suelo",
      "Brazos relajados, hombros bajos",
    ],
    physiologicalObjective: "Elevar Tc corporal a 38°C y activar sistema cardiovascular",
    equipment: "Pista / exterior",
    safeForInjury: true,
  },
  {
    id: "wu-02",
    name: "Movilidad articular dinámica",
    section: "warmup",
    phase: "balanced",
    vector: "rotational",
    contractionType: "concentric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Preparación articular de cadera, rodilla y tobillo para el gesto deportivo",
    defaultSets: 1,
    defaultReps: 10,
    defaultDuration: null,
    defaultRest: 0,
    intensityLevel: "low",
    coachingCues: [
      "Movimientos controlados, amplitud progresiva",
      "Círculos de cadera en ambas direcciones",
      "Rotaciones torácicas sin compensar con lumbar",
    ],
    physiologicalObjective: "Aumentar rango de movimiento funcional y lubricar superficies articulares",
    equipment: "Sin material",
    safeForInjury: true,
  },
  {
    id: "wu-03",
    name: "Skipping y variantes",
    section: "warmup",
    phase: "explode",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 2,
    fatigueGenerated: "low",
    transfer: "Patrón de carrera de alta frecuencia, reclutamiento de flexores de cadera",
    defaultSets: 3,
    defaultReps: null,
    defaultDuration: 20,
    defaultRest: 30,
    intensityLevel: "low",
    coachingCues: [
      "Rodilla al frente, no al techo",
      "Contacto suave y rápido con el suelo",
      "Mantén el tronco erecto y estable",
    ],
    physiologicalObjective: "Activación neuromuscular del tren inferior y coordinación",
    equipment: "Sin material",
    safeForInjury: true,
  },
  {
    id: "wu-04",
    name: "Carrera lateral cruzada",
    section: "warmup",
    phase: "drive",
    vector: "lateral",
    contractionType: "concentric",
    neuromuscularLoad: 2,
    fatigueGenerated: "low",
    transfer: "Desplazamientos defensivos y cambios de dirección laterales",
    defaultSets: 3,
    defaultReps: null,
    defaultDuration: 20,
    defaultRest: 30,
    intensityLevel: "low",
    coachingCues: [
      "Cadera baja durante el desplazamiento",
      "No cruzar los pies, mantén base estable",
      "Brazos activos para generar equilibrio",
    ],
    physiologicalObjective: "Activar cadena abductora/aductora y reflejos posturales",
    equipment: "Sin material",
    safeForInjury: true,
  },

  // ─── ACTIVATION ───────────────────────────────────────────────────────────
  {
    id: "act-load-01",
    name: "Sentadilla isométrica en pared",
    section: "activation",
    phase: "load",
    vector: "vertical",
    contractionType: "isometric",
    neuromuscularLoad: 2,
    fatigueGenerated: "low",
    transfer: "Tolerancia a la postura defensiva y resistencia muscular de cuádriceps",
    defaultSets: 3,
    defaultReps: null,
    defaultDuration: 45,
    defaultRest: 60,
    intensityLevel: "medium",
    coachingCues: [
      "90° en rodilla y cadera",
      "Presiona los pies contra el suelo",
      "Respiración continua, no contener el aliento",
    ],
    physiologicalObjective: "Activación isométrica de cuádriceps y glúteos, reclutamiento de UM lentas",
    equipment: "Pared",
    safeForInjury: true,
  },
  {
    id: "act-load-02",
    name: "Puente de glúteos con carga",
    section: "activation",
    phase: "load",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 2,
    fatigueGenerated: "low",
    transfer: "Fuerza posterior de cadera, base para aceleraciones y frenadas",
    defaultSets: 3,
    defaultReps: 12,
    defaultDuration: null,
    defaultRest: 60,
    intensityLevel: "medium",
    coachingCues: [
      "Aprieta glúteos en la parte superior",
      "Rodillas alineadas con los pies",
      "Pelvis neutra, no hiperextender lumbar",
    ],
    physiologicalObjective: "Activación selectiva de glúteo mayor e isquiosurales proximales",
    equipment: "Colchoneta / disco",
    safeForInjury: true,
  },
  {
    id: "act-load-03",
    name: "RDL excéntrico unilateral",
    section: "activation",
    phase: "load",
    vector: "horizontal",
    contractionType: "eccentric",
    neuromuscularLoad: 3,
    fatigueGenerated: "medium",
    transfer: "Profilaxis de isquiosurales, base de fuerza posterior en cambios de dirección",
    defaultSets: 3,
    defaultReps: 8,
    defaultDuration: null,
    defaultRest: 90,
    intensityLevel: "medium",
    coachingCues: [
      "Fase excéntrica de 3-4 segundos",
      "Cadera atrás, no inclinar el tronco",
      "Pie de apoyo ligeramente flexionado",
    ],
    physiologicalObjective: "Hipertrofia excéntrica de isquiosurales, protección LCA/tendón",
    equipment: "Mancuerna / kettlebell",
    safeForInjury: false,
  },
  {
    id: "act-exp-01",
    name: "Squat jump con pausa",
    section: "activation",
    phase: "explode",
    vector: "vertical",
    contractionType: "plyometric",
    neuromuscularLoad: 3,
    fatigueGenerated: "medium",
    transfer: "Potencia de salto, segunda aceleración, duelos aéreos",
    defaultSets: 3,
    defaultReps: 6,
    defaultDuration: null,
    defaultRest: 90,
    intensityLevel: "high",
    coachingCues: [
      "Pausa 2s en posición baja antes del salto",
      "Extensión completa de tobillo al saltar",
      "Aterrizaje suave, amortiguando en cadera",
    ],
    physiologicalObjective: "Activación del sistema neuromuscular explosivo, reclutamiento de UM rápidas",
    equipment: "Sin material",
    safeForInjury: false,
  },
  {
    id: "act-exp-02",
    name: "Salto al cajón (Box Jump)",
    section: "activation",
    phase: "explode",
    vector: "vertical",
    contractionType: "plyometric",
    neuromuscularLoad: 3,
    fatigueGenerated: "medium",
    transfer: "Producción de fuerza vertical máxima, remate de cabeza, duelos",
    defaultSets: 4,
    defaultReps: 5,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "high",
    coachingCues: [
      "Impulso máximo con brazos",
      "Aterrizaje bipodal y estable sobre el cajón",
      "Bajar caminando, no saltando hacia atrás",
    ],
    physiologicalObjective: "Potencia máxima de tren inferior, reducir tiempo de producción de fuerza",
    equipment: "Cajón pliométrico (40-60cm)",
    safeForInjury: false,
  },
  {
    id: "act-drive-01",
    name: "Hip Thrust con barra",
    section: "activation",
    phase: "drive",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 3,
    fatigueGenerated: "medium",
    transfer: "Fuerza de propulsión horizontal, primera aceleración, transiciones ofensivas",
    defaultSets: 4,
    defaultReps: 8,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "high",
    coachingCues: [
      "Aprieta glúteos en la extensión completa",
      "Barbilla al pecho, mirada al techo",
      "Rodillas a 90° con los pies alineados",
    ],
    physiologicalObjective: "Fuerza máxima de extensión de cadera en vector horizontal, base de aceleración",
    equipment: "Banco / barra / disco",
    safeForInjury: false,
  },
  {
    id: "act-drive-02",
    name: "Sled Push pesado",
    section: "activation",
    phase: "drive",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Producción de fuerza horizontal máxima, mecánica de aceleración",
    defaultSets: 4,
    defaultReps: null,
    defaultDuration: null,
    defaultRest: 180,
    intensityLevel: "max",
    coachingCues: [
      "Inclinación corporal de 45°",
      "Pasos cortos y potentes",
      "Empuja desde el suelo, no arrastra",
    ],
    physiologicalObjective: "Fuerza aplicada máxima en vector horizontal, activación de glúteos y extensores",
    equipment: "Trineo / sled",
    safeForInjury: false,
  },
  {
    id: "act-bal-01",
    name: "Monster Walk con banda",
    section: "activation",
    phase: "balanced",
    vector: "lateral",
    contractionType: "isometric",
    neuromuscularLoad: 2,
    fatigueGenerated: "low",
    transfer: "Estabilización de rodilla y cadera, prevención de valgo dinámico",
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: null,
    defaultRest: 60,
    intensityLevel: "low",
    coachingCues: [
      "Banda a nivel de tobillos",
      "Rodillas ligeramente flexionadas",
      "Pasos laterales cortos y controlados",
    ],
    physiologicalObjective: "Activación de glúteo medio, estabilización lateral de pelvis",
    equipment: "Banda elástica",
    safeForInjury: true,
  },

  // ─── PLYOMETRICS ──────────────────────────────────────────────────────────
  {
    id: "plio-exp-01",
    name: "Drop Jump reactivo",
    section: "plyometrics",
    phase: "explode",
    vector: "vertical",
    contractionType: "reactive",
    neuromuscularLoad: 5,
    fatigueGenerated: "high",
    transfer: "Mejora del RSI, saltos reactivos en duelos aéreos y rechaces",
    defaultSets: 4,
    defaultReps: 5,
    defaultDuration: null,
    defaultRest: 180,
    intensityLevel: "max",
    coachingCues: [
      "Tiempo de contacto mínimo (<200ms)",
      "No amortiguación excesiva, aterrizaje reactivo",
      "Brazos explosivos hacia arriba",
    ],
    physiologicalObjective: "Maximizar RSI, optimizar ciclo estiramiento-acortamiento, potencia reactiva",
    equipment: "Cajón (20-30cm)",
    safeForInjury: false,
  },
  {
    id: "plio-exp-02",
    name: "Salto horizontal máximo (Standing broad jump)",
    section: "plyometrics",
    phase: "explode",
    vector: "horizontal",
    contractionType: "plyometric",
    neuromuscularLoad: 4,
    fatigueGenerated: "medium",
    transfer: "Primera aceleración, salidas de presión, arranques ofensivos",
    defaultSets: 4,
    defaultReps: 4,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "max",
    coachingCues: [
      "Impulso máximo de brazos hacia adelante",
      "Ángulo de despegue 45°",
      "Aterrizaje bípedo estabilizado",
    ],
    physiologicalObjective: "Potencia máxima en vector horizontal-oblicuo, transferencia directa a aceleración",
    equipment: "Sin material",
    safeForInjury: false,
  },
  {
    id: "plio-exp-03",
    name: "Bounding alternado",
    section: "plyometrics",
    phase: "explode",
    vector: "horizontal",
    contractionType: "reactive",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Zancada explosiva, aceleraciones largas, velocidad máxima",
    defaultSets: 4,
    defaultReps: null,
    defaultDuration: null,
    defaultRest: 150,
    intensityLevel: "max",
    coachingCues: [
      "Cada zancada con máximo impulso",
      "Rodilla delantera a 90° en vuelo",
      "Brazos opuestos sincronizados",
    ],
    physiologicalObjective: "Elasticidad y potencia de la zancada, patrón neuromuscular de carrera",
    equipment: "Pista de 30-40m",
    safeForInjury: false,
  },
  {
    id: "plio-load-01",
    name: "Squat Jump lastrado",
    section: "plyometrics",
    phase: "load",
    vector: "vertical",
    contractionType: "plyometric",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Potencia con carga, tolerancia muscular a esfuerzos explosivos continuados",
    defaultSets: 4,
    defaultReps: 6,
    defaultDuration: null,
    defaultRest: 150,
    intensityLevel: "high",
    coachingCues: [
      "Profundidad consistente en cada rep",
      "Extensión explosiva de tobillo",
      "Carga ≤20% del peso corporal",
    ],
    physiologicalObjective: "Potencia de fuerza con carga moderada, hipertrofia de UM rápidas",
    equipment: "Chaleco lastrado / barra",
    safeForInjury: false,
  },
  {
    id: "plio-drive-01",
    name: "Saltos de valla (Hurdle hops)",
    section: "plyometrics",
    phase: "drive",
    vector: "horizontal",
    contractionType: "reactive",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Frecuencia de zancada, reactividad en transiciones defensivas",
    defaultSets: 4,
    defaultReps: 5,
    defaultDuration: null,
    defaultRest: 150,
    intensityLevel: "high",
    coachingCues: [
      "Mínimo tiempo de contacto entre vallas",
      "Proyección de rodillas hacia adelante",
      "Brazos activos en cada impulso",
    ],
    physiologicalObjective: "Potencia reactiva horizontal, reducción tiempo de contacto en zancada",
    equipment: "Vallas 30-50cm",
    safeForInjury: false,
  },

  // ─── STRENGTH ─────────────────────────────────────────────────────────────
  {
    id: "str-load-01",
    name: "Sentadilla trasera",
    section: "strength",
    phase: "load",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 5,
    fatigueGenerated: "high",
    transfer: "Fuerza máxima de tren inferior, base para todas las acciones explosivas",
    defaultSets: 4,
    defaultReps: 5,
    defaultDuration: null,
    defaultRest: 240,
    intensityLevel: "max",
    coachingCues: [
      "Fase excéntrica de 3 segundos",
      "Rodillas siguen la línea de los pies",
      "Pecho arriba, barra baja sobre trapecios",
    ],
    physiologicalObjective: "Fuerza máxima de extensores de rodilla y cadera, base neurológica de potencia",
    equipment: "Barra olímpica / rack",
    safeForInjury: false,
  },
  {
    id: "str-load-02",
    name: "Sentadilla búlgara (RFESS)",
    section: "strength",
    phase: "load",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Fuerza unilateral de tren inferior, estabilidad pélvica en carrera",
    defaultSets: 4,
    defaultReps: 8,
    defaultDuration: null,
    defaultRest: 180,
    intensityLevel: "high",
    coachingCues: [
      "Pie trasero en apoyo suave sobre banco",
      "Desciende verticalmente, no hacia adelante",
      "Rodilla delantera alineada con el 2° dedo",
    ],
    physiologicalObjective: "Fuerza unilateral de cuádriceps y glúteos, corrección de desequilibrios",
    equipment: "Banco / mancuernas",
    safeForInjury: false,
  },
  {
    id: "str-load-03",
    name: "Prensa de piernas",
    section: "strength",
    phase: "load",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Fuerza de extensión de rodilla sin carga espinal, volumen de trabajo",
    defaultSets: 4,
    defaultReps: 10,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "high",
    coachingCues: [
      "Pies a la anchura de hombros en la plataforma",
      "No bloquear las rodillas en extensión completa",
      "Control excéntrico de 2 segundos",
    ],
    physiologicalObjective: "Hipertrofia funcional de cuádriceps, volumen de trabajo sin riesgo espinal",
    equipment: "Máquina de prensa",
    safeForInjury: true,
  },
  {
    id: "str-exp-01",
    name: "Hang Power Clean",
    section: "strength",
    phase: "explode",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 5,
    fatigueGenerated: "high",
    transfer: "Potencia máxima en triple extensión, aceleraciones, saltos",
    defaultSets: 5,
    defaultReps: 3,
    defaultDuration: null,
    defaultRest: 240,
    intensityLevel: "max",
    coachingCues: [
      "Tirón violento de caderas, no de brazos",
      "Tracción vertical con codos altos",
      "Recepción en posición de sentadilla media",
    ],
    physiologicalObjective: "Potencia máxima de triple extensión, activación del SNC, RFD máxima",
    equipment: "Barra olímpica",
    safeForInjury: false,
  },
  {
    id: "str-exp-02",
    name: "Cargada de potencia (Power Clean)",
    section: "strength",
    phase: "explode",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 5,
    fatigueGenerated: "high",
    transfer: "Máxima producción de potencia, transferencia directa a velocidad y salto",
    defaultSets: 5,
    defaultReps: 2,
    defaultDuration: null,
    defaultRest: 300,
    intensityLevel: "max",
    coachingCues: [
      "Arranca desde el suelo con espaldas rectas",
      "La barra roza el cuerpo todo el recorrido",
      "Tirón de caderas explosivo en zona media",
    ],
    physiologicalObjective: "Máxima RFD, integración de cadena cinética completa, potencia pico",
    equipment: "Barra olímpica / plataforma",
    safeForInjury: false,
  },
  {
    id: "str-drive-01",
    name: "Peso muerto rumano (RDL)",
    section: "strength",
    phase: "drive",
    vector: "horizontal",
    contractionType: "eccentric",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Fuerza posterior de cadera, propulsión horizontal, prevención de lesiones de isquios",
    defaultSets: 4,
    defaultReps: 6,
    defaultDuration: null,
    defaultRest: 180,
    intensityLevel: "high",
    coachingCues: [
      "Cadera atrás, espalda recta todo el recorrido",
      "Fase excéntrica 3-4 segundos",
      "Barra cerca del cuerpo en todo momento",
    ],
    physiologicalObjective: "Fuerza excéntrica de isquiosurales y glúteos, prevención de lesiones",
    equipment: "Barra / mancuernas",
    safeForInjury: false,
  },
  {
    id: "str-drive-02",
    name: "Step-up explosivo unilateral",
    section: "strength",
    phase: "drive",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 3,
    fatigueGenerated: "medium",
    transfer: "Fuerza unilateral de arranque, subidas a alta velocidad, primera zancada",
    defaultSets: 4,
    defaultReps: 8,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "high",
    coachingCues: [
      "Sube explosivamente desde el pie de apoyo",
      "Rodilla opuesta al pecho en subida",
      "No impulsarte con el pie trasero",
    ],
    physiologicalObjective: "Potencia unilateral de glúteo y extensores, patrón de carrera",
    equipment: "Cajón 40-50cm / mancuernas",
    safeForInjury: false,
  },
  {
    id: "str-drive-03",
    name: "Good Morning con barra",
    section: "strength",
    phase: "drive",
    vector: "horizontal",
    contractionType: "eccentric",
    neuromuscularLoad: 4,
    fatigueGenerated: "medium",
    transfer: "Fuerza de cadera en vector horizontal, base de propulsión y sprint",
    defaultSets: 3,
    defaultReps: 8,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "medium",
    coachingCues: [
      "Cabeza y espalda alineadas en todo momento",
      "Bisagra de cadera pura, no doblar rodillas",
      "Aprieta isquios en retorno",
    ],
    physiologicalObjective: "Fuerza de extensión de cadera, resistencia de columna lumbar",
    equipment: "Barra olímpica",
    safeForInjury: false,
  },

  // ─── SPEED ────────────────────────────────────────────────────────────────
  {
    id: "spd-01",
    name: "Aceleraciones 10m (x6)",
    section: "speed",
    phase: "drive",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Primera fase de aceleración, mecánica de sprint inicial",
    defaultSets: 6,
    defaultReps: null,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "max",
    coachingCues: [
      "Inclinación de 45° en los primeros pasos",
      "Pasos cortos y frecuentes al inicio",
      "Brazos potentes y opuestos a las piernas",
    ],
    physiologicalObjective: "Mecánica de aceleración, RFD aplicada, potencia de primer paso",
    equipment: "Pista de 20m",
    safeForInjury: false,
  },
  {
    id: "spd-02",
    name: "Sprints máximos 30m",
    section: "speed",
    phase: "explode",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 5,
    fatigueGenerated: "high",
    transfer: "Velocidad máxima, acciones de sprint en transiciones",
    defaultSets: 5,
    defaultReps: null,
    defaultDuration: null,
    defaultRest: 240,
    intensityLevel: "max",
    coachingCues: [
      "Máxima velocidad desde los primeros pasos",
      "Fase de velocidad máxima entre 20-30m",
      "Zancada abierta, frecuencia máxima",
    ],
    physiologicalObjective: "Velocidad máxima, activación máxima del SNC, patrón de zancada óptimo",
    equipment: "Pista de 40m",
    safeForInjury: false,
  },
  {
    id: "spd-03",
    name: "Cambios de dirección 5-10-5",
    section: "speed",
    phase: "drive",
    vector: "lateral",
    contractionType: "reactive",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Agilidad en transiciones defensivas, reposicionamiento táctico",
    defaultSets: 6,
    defaultReps: null,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "max",
    coachingCues: [
      "Frenada activa con el pie exterior",
      "Centro de gravedad bajo en el cambio",
      "Primer paso explosivo hacia la nueva dirección",
    ],
    physiologicalObjective: "Agilidad reglamentaria, fuerza excéntrica de frenada lateral",
    equipment: "Conos",
    safeForInjury: false,
  },
  {
    id: "spd-04",
    name: "Flying sprint 10m (entrada 20m)",
    section: "speed",
    phase: "explode",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 5,
    fatigueGenerated: "high",
    transfer: "Velocidad máxima absoluta, mecánica de velocidad pura",
    defaultSets: 4,
    defaultReps: null,
    defaultDuration: null,
    defaultRest: 300,
    intensityLevel: "max",
    coachingCues: [
      "Los 20m de entrada son para alcanzar Vmax",
      "En los 10m de medición: zancada máxima",
      "Brazos potentes, no cruzar línea central del cuerpo",
    ],
    physiologicalObjective: "Vmax absoluta, mecánica de carrera a alta velocidad, activación SNC máxima",
    equipment: "Pista de 40m / cronómetro",
    safeForInjury: false,
  },
  {
    id: "spd-05",
    name: "Sprint en pendiente positiva",
    section: "speed",
    phase: "load",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Fuerza-velocidad en aceleración, mecánica de inclinación",
    defaultSets: 6,
    defaultReps: null,
    defaultDuration: null,
    defaultRest: 150,
    intensityLevel: "high",
    coachingCues: [
      "Mayor inclinación natural por pendiente",
      "Pasos cortos y potentes",
      "Pendiente entre 5-10%",
    ],
    physiologicalObjective: "Fuerza aplicada en carrera, estímulo de potencia sin sobrecargar SNC",
    equipment: "Cuesta / colina",
    safeForInjury: false,
  },

  // ─── PREVENTIVE ───────────────────────────────────────────────────────────
  {
    id: "prev-01",
    name: "Nordic Hamstring Curl",
    section: "preventive",
    phase: "load",
    vector: "horizontal",
    contractionType: "eccentric",
    neuromuscularLoad: 4,
    fatigueGenerated: "high",
    transfer: "Prevención primaria de lesiones de isquiosurales",
    defaultSets: 3,
    defaultReps: 6,
    defaultDuration: null,
    defaultRest: 120,
    intensityLevel: "high",
    coachingCues: [
      "Descenso lento y controlado (4-5 segundos)",
      "Caída controlada hacia el suelo",
      "Retorno con ayuda de manos",
    ],
    physiologicalObjective: "Fuerza excéntrica máxima de isquiosurales, prevención de rotura muscular",
    equipment: "Banco fijo / compañero",
    safeForInjury: false,
  },
  {
    id: "prev-02",
    name: "Estabilización de rodilla (VMO)",
    section: "preventive",
    phase: "balanced",
    vector: "vertical",
    contractionType: "isometric",
    neuromuscularLoad: 2,
    fatigueGenerated: "low",
    transfer: "Prevención de lesiones de rodilla (LCA, meniscos), control motor de valgo",
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: null,
    defaultRest: 60,
    intensityLevel: "low",
    coachingCues: [
      "Sentadilla monopodal controlada",
      "Rodilla alineada, sin valgo dinámico",
      "Espejo para control visual",
    ],
    physiologicalObjective: "Activación selectiva de VMO, control neuromuscular de rodilla",
    equipment: "Sin material / espejo",
    safeForInjury: true,
  },
  {
    id: "prev-03",
    name: "Core Plank progresivo",
    section: "preventive",
    phase: "balanced",
    vector: "horizontal",
    contractionType: "isometric",
    neuromuscularLoad: 2,
    fatigueGenerated: "low",
    transfer: "Estabilidad de core en todas las acciones deportivas",
    defaultSets: 3,
    defaultReps: null,
    defaultDuration: 45,
    defaultRest: 60,
    intensityLevel: "medium",
    coachingCues: [
      "Cuerpo en línea recta de cabeza a talones",
      "Ombligo contraído hacia la columna",
      "Sin bloquear la respiración",
    ],
    physiologicalObjective: "Rigidez de core, estabilización lumbo-pélvica en esfuerzo",
    equipment: "Colchoneta",
    safeForInjury: true,
  },
  {
    id: "prev-04",
    name: "Isométrico de aductores (Copenhagen)",
    section: "preventive",
    phase: "drive",
    vector: "lateral",
    contractionType: "isometric",
    neuromuscularLoad: 3,
    fatigueGenerated: "medium",
    transfer: "Prevención de pubalgia y lesiones de aductores",
    defaultSets: 3,
    defaultReps: null,
    defaultDuration: 30,
    defaultRest: 90,
    intensityLevel: "medium",
    coachingCues: [
      "Cuerpo en plancha lateral",
      "Pierna inferior en apoyo lateral",
      "Mantén la pelvis elevada durante todo el tiempo",
    ],
    physiologicalObjective: "Fuerza isométrica de aductores, prevención de pubalgia",
    equipment: "Banco",
    safeForInjury: false,
  },
  {
    id: "prev-05",
    name: "Balance monopodal en superficie inestable",
    section: "preventive",
    phase: "balanced",
    vector: "vertical",
    contractionType: "isometric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Propiocepción de tobillo, prevención de esguinces",
    defaultSets: 3,
    defaultReps: null,
    defaultDuration: 30,
    defaultRest: 30,
    intensityLevel: "low",
    coachingCues: [
      "Ojos cerrados para mayor estímulo propioceptivo",
      "Pie de apoyo ligeramente flexionado",
      "Mantén pelvis nivelada",
    ],
    physiologicalObjective: "Activación de propioceptores de tobillo, control postural dinámico",
    equipment: "BOSU / colchoneta",
    safeForInjury: true,
  },
  {
    id: "prev-06",
    name: "Estiramiento excéntrico de gemelos",
    section: "preventive",
    phase: "load",
    vector: "vertical",
    contractionType: "eccentric",
    neuromuscularLoad: 2,
    fatigueGenerated: "low",
    transfer: "Prevención de tendinopatía aquílea y lesiones de gemelo",
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: null,
    defaultRest: 60,
    intensityLevel: "low",
    coachingCues: [
      "Descenso lento y controlado (3 segundos)",
      "Subida rápida en bipodal si hay dolor",
      "Rango completo de tobillo",
    ],
    physiologicalObjective: "Fuerza excéntrica de tendón de Aquiles y gemelos, prevención tendinopatía",
    equipment: "Escalón",
    safeForInjury: true,
  },

  // ─── COOLDOWN ─────────────────────────────────────────────────────────────
  {
    id: "cd-01",
    name: "Trote suave de vuelta a la calma",
    section: "cooldown",
    phase: "balanced",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Retorno progresivo a reposo, eliminación de metabolitos",
    defaultSets: 1,
    defaultReps: null,
    defaultDuration: 300,
    defaultRest: 0,
    intensityLevel: "low",
    coachingCues: [
      "Ritmo muy suave, conversacional",
      "Pasos cortos y relajados",
      "Respiración nasal si es posible",
    ],
    physiologicalObjective: "Reducción gradual de FC, activación del sistema parasimpático",
    equipment: "Pista",
    safeForInjury: true,
  },
  {
    id: "cd-02",
    name: "Estiramientos estáticos de cuádriceps e isquios",
    section: "cooldown",
    phase: "load",
    vector: "vertical",
    contractionType: "isometric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Recuperación de rango articular, bienestar muscular",
    defaultSets: 2,
    defaultReps: null,
    defaultDuration: 30,
    defaultRest: 15,
    intensityLevel: "low",
    coachingCues: [
      "Estira hasta percibir tensión suave, no dolor",
      "Mantén la posición sin rebotes",
      "Respiración lenta y profunda",
    ],
    physiologicalObjective: "Reducción de tensión muscular, recuperación de longitud muscular en reposo",
    equipment: "Colchoneta",
    safeForInjury: true,
  },
  {
    id: "cd-03",
    name: "Foam roller de tren inferior",
    section: "cooldown",
    phase: "balanced",
    vector: "horizontal",
    contractionType: "isometric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Recuperación miofascial, reducción de dolor muscular tardío",
    defaultSets: 1,
    defaultReps: null,
    defaultDuration: 180,
    defaultRest: 0,
    intensityLevel: "low",
    coachingCues: [
      "Rodajes lentos de 2-3cm/segundo",
      "Pausa en puntos de tensión 20-30 seg",
      "No pasar por articulaciones",
    ],
    physiologicalObjective: "Liberación miofascial, mejora de la circulación local, recuperación",
    equipment: "Foam roller",
    safeForInjury: true,
  },
  {
    id: "cd-04",
    name: "Respiración diafragmática",
    section: "cooldown",
    phase: "balanced",
    vector: "horizontal",
    contractionType: "isometric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Activación parasimpática, recuperación del SNC",
    defaultSets: 1,
    defaultReps: null,
    defaultDuration: 180,
    defaultRest: 0,
    intensityLevel: "low",
    coachingCues: [
      "Inspiración nasal 4 segundos",
      "Retención 4 segundos",
      "Exhalación bucal 8 segundos",
    ],
    physiologicalObjective: "Activación del sistema nervioso parasimpático, recuperación post-esfuerzo",
    equipment: "Colchoneta",
    safeForInjury: true,
  },

  // ─── READAPTATION SPECIFIC ────────────────────────────────────────────────
  {
    id: "read-01",
    name: "Sentadilla en agua / piscina",
    section: "strength",
    phase: "load",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Reintroducción de carga en descarga articular",
    defaultSets: 3,
    defaultReps: 15,
    defaultDuration: null,
    defaultRest: 60,
    intensityLevel: "low",
    coachingCues: [
      "Profundidad según tolerancia del jugador",
      "Control constante del dolor",
      "Progresión: del agua al suelo",
    ],
    physiologicalObjective: "Reintroducción de activación muscular sin carga articular completa",
    equipment: "Piscina",
    safeForInjury: true,
  },
  {
    id: "read-02",
    name: "Carrera en agua (Aquajogging)",
    section: "warmup",
    phase: "balanced",
    vector: "horizontal",
    contractionType: "concentric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Mantenimiento de patrón de carrera sin impacto",
    defaultSets: 1,
    defaultReps: null,
    defaultDuration: 1200,
    defaultRest: 0,
    intensityLevel: "low",
    coachingCues: [
      "Imita patrón de carrera en tierra",
      "Mantén el tronco erecto",
      "FC objetivo 120-130 ppm",
    ],
    physiologicalObjective: "Mantenimiento cardiovascular y neuromuscular sin impacto articular",
    equipment: "Piscina / cinturón de flotación",
    safeForInjury: true,
  },
  {
    id: "read-03",
    name: "Bicicleta estática progresiva",
    section: "warmup",
    phase: "balanced",
    vector: "vertical",
    contractionType: "concentric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Reactivación cardiovascular y muscular en readaptación",
    defaultSets: 1,
    defaultReps: null,
    defaultDuration: 900,
    defaultRest: 0,
    intensityLevel: "low",
    coachingCues: [
      "Sin dolor durante el pedaleo",
      "Incremento gradual de resistencia",
      "FC no superar 140 ppm en fase inicial",
    ],
    physiologicalObjective: "Reintroducción de carga cardiovascular, activación muscular progresiva",
    equipment: "Bicicleta estática",
    safeForInjury: true,
  },
  {
    id: "read-04",
    name: "Ejercicios de movilidad articular específica",
    section: "activation",
    phase: "balanced",
    vector: "rotational",
    contractionType: "isometric",
    neuromuscularLoad: 1,
    fatigueGenerated: "low",
    transfer: "Recuperación de rango de movimiento en zona lesionada",
    defaultSets: 3,
    defaultReps: 10,
    defaultDuration: null,
    defaultRest: 30,
    intensityLevel: "low",
    coachingCues: [
      "Movimientos sin dolor en todo el recorrido",
      "Aumentar rango progresivamente",
      "Comunicación constante con el preparador",
    ],
    physiologicalObjective: "Recuperación de rango articular, lubricación sinovial, movilidad funcional",
    equipment: "Sin material",
    safeForInjury: true,
  },
];

export function getExercisesBySection(section: Section): Exercise[] {
  return EXERCISES.filter(e => e.section === section);
}

export function getExercisesByPhase(phase: Phase, section?: Section): Exercise[] {
  return EXERCISES.filter(e =>
    (e.phase === phase || e.phase === "balanced") &&
    (section ? e.section === section : true),
  );
}

export function getSafeExercises(): Exercise[] {
  return EXERCISES.filter(e => e.safeForInjury);
}
